Blender 2.80 (sub 46) (hash 18e5540a48b6 built 05/03/2019 17:06)
Read prefs: C:\Users\baris\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: c:\apps\blender-2.80-18e5540a48b6-win64\2.80\python
Warning: 'ToolsPanel' doesn't contain '_PT_' with prefix & suffix
Warning: 'yaam.blend_link' doesn't contain '_MT_' with prefix & suffix
Warning: 'yaam.blend_append' doesn't contain '_MT_' with prefix & suffix
Warning: 'pan.navigation1' doesn't contain '_PT_' with prefix & suffix
Warning: 'pan.navigation1' doesn't contain '_PT_' with prefix & suffix
Warning: 'view3d.manipulator_of' doesn't contain '_MT_' with prefix & suffix
Warning: 'pie.object_mode_of' doesn't contain '_MT_' with prefix & suffix
Warning: 'view3d.pivot_of' doesn't contain '_MT_' with prefix & suffix
Warning: 'pie.shade_of' doesn't contain '_MT_' with prefix & suffix
Warning: 'view3d.snap_of' doesn't contain '_MT_' with prefix & suffix
Warning: 'VIEW3D_PIE_view_more_of' doesn't contain '_MT_' with prefix & suffix
Warning: 'pie.view_of' doesn't contain '_MT_' with prefix & suffix
Warning: 'CLIP_PIE_geometry_reconstruction' doesn't contain '_MT_' with prefix & suffix
Warning: 'CLIP_PIE_tracking_pie' doesn't contain '_MT_' with prefix & suffix
Warning: 'CLIP_PIE_display_pie' doesn't contain '_MT_' with prefix & suffix
Warning: 'CLIP_PIE_proxy_pie' doesn't contain '_MT_' with prefix & suffix
Warning: 'CLIP_PIE_marker_pie' doesn't contain '_MT_' with prefix & suffix
Warning: 'CLIP_PIE_solver_pie' doesn't contain '_MT_' with prefix & suffix
Warning: 'CLIP_PIE_refine_pie' doesn't contain '_MT_' with prefix & suffix
Warning: 'CLIP_PIE_reconstruction_pie' doesn't contain '_MT_' with prefix & suffix
Warning: 'CLIP_PIE_clipsetup_pie' doesn't contain '_MT_' with prefix & suffix
Warning: 'CLIP_PIE_timecontrol_pie' doesn't contain '_MT_' with prefix & suffix
Warning: 'pbr_previews' doesn't contain '_PT_' with prefix & suffix
Warning: 'PBRMaterialPanelNode' doesn't contain '_PT_' with prefix & suffix
Error: Cannot read file 'C:\assets\04102019_BlendSwap\unpacked\Shipwright.0006.blend': No such file or directory
Traceback (most recent call last):
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons\archimesh\__init__.py", line 70, in <module>
    from . import achm_main_panel
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons\archimesh\achm_main_panel.py", line 33, in <module>
    from .achm_gltools import *
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons\archimesh\achm_gltools.py", line 41, in <module>
    shader = gpu.shader.from_builtin('2D_UNIFORM_COLOR')
SystemError: GPU functions for drawing are not available in background mode
Traceback (most recent call last):
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\modules\addon_utils.py", line 393, in enable
    mod.register()
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons\bone_selection_sets.py", line 558, in register
    km = wm.keyconfigs.addon.keymaps.new(name='Pose')
AttributeError: 'NoneType' object has no attribute 'keymaps'
Traceback (most recent call last):
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\modules\addon_utils.py", line 393, in enable
    mod.register()
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons\mesh_snap_utilities_line\__init__.py", line 160, in register
    register_snap_tools()
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons\mesh_snap_utilities_line\__init__.py", line 120, in register_snap_tools
    keyconfig_init_from_data(kc_defaultconf, keyconfig_data)
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\modules\bl_keymap_utils\io.py", line 250, in keyconfig_init_from_data
    km = kc.keymaps.new(km_name, **km_args)
AttributeError: 'NoneType' object has no attribute 'keymaps'
Traceback (most recent call last):
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons_contrib\sverchok\__init__.py", line 77, in <module>
    imported_modules = init_architecture(__name__, utils_modules, ui_modules)
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons_contrib\sverchok\core\__init__.py", line 101, in init_architecture
    import_all_modules(imported_modules, mods_bases)
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons_contrib\sverchok\core\__init__.py", line 86, in import_all_modules
    import_modules(mods, base, imported_modules)
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons_contrib\sverchok\core\__init__.py", line 61, in import_modules
    im = importlib.import_module('.{}'.format(m), base)
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons_contrib\sverchok\utils\sv_batch_primitives.py", line 12, in <module>
    uniform_shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
SystemError: GPU functions for drawing are not available in background mode
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\src\Pamux\Pamux.EngTools\Scripts\BlendSanitizer.py", line 7, in <module>
    from Folders import Folders
ModuleNotFoundError: No module named 'Folders'
Exception in module register(): c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons\bone_selection_sets.py
archipack: ready
Exception in module register(): c:\apps\blender-2.80-18e5540a48b6-win64\2.80\scripts\addons\mesh_snap_utilities_line\__init__.py
sv: import settings
sv: import all modules

Blender quit
